name: Build and Store Container Artifact

on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - 'Dockerfile'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-store:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build image
        run: docker build -t vulnerable-code-team1:latest .

      - name: Save image as tar
        run: docker save vulnerable-code-team1:latest -o container-image.tar

      - name: Upload container as artifact
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: container-artifact
          path: container-image.tar
