name: Semgrep SAST Scan

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep@sha256:93963d9295a366f59e4850127b1550400ee7b388f04fe144e4a1f6325d96e01b
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Semgrep scan
        run: |
          semgrep scan \
            --config auto \
            --config p/security-audit \
            --config p/owasp-top-ten \
            --error \
            --sarif \
            --output semgrep-results.sarif

      - name: Upload results as artifact
        if: always()
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: semgrep-results
          path: semgrep-results.sarif
